export enum Colors {
  Black = "black",
  Blue = "blue",
  Brown = "brown",
  Coral = "coral",
  Cyan = "cyan",
  DarkGreen = "darkgreen",
  Gold = "gold",
  Gray = "gray",
  Green = "green",
  GreenYellow = "greenyellow",
  Indigo = "indigo",
  Lavender = "lavender",
  LightBlue = "lightblue",
  Maroon = "maroon",
  Olive = "olive",
  Orange = "orange",
  Pink = "pink",
  Purple = "purple",
  Red = "red",
  Salmon = "salmon",
  Silver = "silver",
  Teal = "teal",
  White = "white",
  Yellow = "yellow",
}
